<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $preview ? 'Vista previa' : 'Simple View' }}</title>
<style>
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#000;color:#fff;font-family:system-ui,sans-serif;user-select:none}.stage{position:fixed;inset:0;display:grid;background:#000}.stage.preview{position:relative;width:min(100vw,1280px);aspect-ratio:16/9;margin:auto;top:50%;transform:translateY(-50%);box-shadow:0 0 0 1px #444}.zone{position:relative;overflow:hidden;background:#000}.zone .item{position:absolute;inset:0;width:100%;height:100%;opacity:0;transition-property:opacity;will-change:opacity}.zone .item.active{opacity:1}.zone img,.zone video{width:100%;height:100%;display:block;background:#000}.zone video{backface-visibility:hidden;transform:translateZ(0)}.full{grid-template:1fr/1fr}.columns{grid-template:1fr/1fr 1fr}.rows{grid-template:1fr 1fr/1fr}.grid{grid-template:1fr 1fr/1fr 1fr}.right_sidebar{grid-template:1fr 1fr/7fr 3fr}.right_sidebar .zone:nth-child(3){grid-column:2;grid-row:1/3}.left_sidebar{grid-template:1fr 1fr/3fr 7fr}.left_sidebar .zone:nth-child(3){grid-column:1;grid-row:1/3}.left_sidebar .zone:nth-child(1),.left_sidebar .zone:nth-child(2){grid-column:2}.badge{position:fixed;z-index:10;top:12px;right:12px;background:#111c;padding:6px 10px;border-radius:6px;font-size:13px}.offline{position:fixed;z-index:12;bottom:8px;right:8px;width:8px;height:8px;border-radius:50%;background:#f59e0b;display:none}.offline.buffering{display:block!important;background:#3b82f6;animation:pulse 1s ease-in-out infinite}@keyframes pulse{50%{opacity:.35}}
</style></head><body><div id="stage" class="stage {{ $preview?'preview':'' }}"></div>@if($preview)<div class="badge">Vista previa</div>@endif<div id="offline" class="offline"></div>
<script>
const PREVIEW=@json($preview), VIDEO_START_BUFFER_SECONDS=@json((int) config('simpleview.video_start_buffer_seconds')), VIDEO_MAX_START_WAIT_MS=@json((int) config('simpleview.video_max_start_wait_seconds')*1000), VIDEO_STALL_REPORT_MS=@json((int) config('simpleview.video_stall_report_seconds')*1000), PRELOAD_NEXT_VIDEO=@json((bool) config('simpleview.video_preload_next')), stage=document.querySelector('#stage'), offline=document.querySelector('#offline');let config=null,version=0,reloadToken=@json($reloadToken),runners=[],connected=true,currentItems={};
const qs=new URLSearchParams(location.search), configUrl=PREVIEW?'/api/preview/config?layout='+encodeURIComponent(qs.get('layout')||''):'/api/display/config';
function stop(){runners.forEach(r=>r());runners=[];currentItems={};stage.querySelectorAll('video').forEach(v=>{v.pause();v.removeAttribute('src');v.load()})}
function render(c){stop();config=c;version=c?.version||0;stage.className='stage '+(PREVIEW?'preview ':'')+(c?.template||'full');stage.innerHTML='';if(!c)return;c.zones.forEach(z=>{const el=document.createElement('div');el.className='zone';stage.appendChild(el);runners.push(runZone(el,z))})}
function fallback(url){stop();stage.innerHTML=url?`<img src="${url}" style="width:100%;height:100%;object-fit:contain">`:'';stage.className='stage full'}
function bufferedAhead(video){const time=video.currentTime||0;for(let i=0;i<video.buffered.length;i++){if(video.buffered.start(i)<=time+.25&&video.buffered.end(i)>time)return video.buffered.end(i)-time}return 0}
function bufferGoal(item){const duration=Math.max(1,(item.duration_ms||0)/1000),bitrate=(item.size||0)*8/duration/1000000;return Math.max(VIDEO_START_BUFFER_SECONDS,Math.min(15,Math.ceil(bitrate/6)))}
function waitForImage(node,isStopped){if(node.complete)return node.decode?node.decode().catch(()=>{}):Promise.resolve();return new Promise((resolve,reject)=>{const done=()=>{cleanup();resolve()},fail=()=>{cleanup();reject(new Error('image'))},cleanup=()=>{node.removeEventListener('load',done);node.removeEventListener('error',fail)};node.addEventListener('load',done,{once:true});node.addEventListener('error',fail,{once:true});if(isStopped()){cleanup();resolve()}})}
function waitForVideo(node,goal,isStopped){return new Promise((resolve,reject)=>{const started=Date.now();let interval=null;const cleanup=()=>{clearInterval(interval);node.removeEventListener('error',fail)},finish=()=>{cleanup();resolve()},fail=()=>{cleanup();reject(new Error('video'))},check=()=>{if(isStopped()){cleanup();return resolve()}const ahead=bufferedAhead(node);if(node.readyState>=HTMLMediaElement.HAVE_FUTURE_DATA&&ahead>=goal)return finish();if(Date.now()-started>=VIDEO_MAX_START_WAIT_MS){if(node.readyState>=HTMLMediaElement.HAVE_FUTURE_DATA&&ahead>=1)return finish();return fail()}};node.addEventListener('error',fail,{once:true});interval=setInterval(check,250);check()})}
function runZone(el,z){
 let stopped=false,currentIndex=-1,timer=null,transitioning=false,active=null,prepared=new Map;
 const release=(node)=>{if(!node)return;if(node.tagName==='VIDEO'){node.pause();node.removeAttribute('src');node.load()}node.remove()};
 const prepare=(index)=>{if(prepared.has(index))return prepared.get(index);const item=z.items[index],node=document.createElement(item.type==='video'?'video':'img');node.className='item';node.style.objectFit=item.fit||'cover';node.dataset.index=String(index);if(item.type==='video'){node.muted=true;node.defaultMuted=true;node.playsInline=true;node.disablePictureInPicture=true;node.disableRemotePlayback=true;node.preload='auto';node.setAttribute('playsinline','');node.setAttribute('preload','auto');node.src=item.url;node.load()}else node.src=item.url;el.appendChild(node);prepared.set(index,node);return node};
 const prepareNext=()=>{if(!PRELOAD_NEXT_VIDEO||z.items.length<2)return;const nextIndex=(currentIndex+1)%z.items.length,nextItem=z.items[nextIndex];if(nextItem.type==='video')prepare(nextIndex)};
 const show=async(index)=>{
  if(stopped||transitioning||!z.items.length)return;transitioning=true;clearTimeout(timer);const item=z.items[index],node=prepare(index),previous=active;
  try{if(item.type==='video'){await waitForVideo(node,bufferGoal(item),()=>stopped);if(stopped)return;await node.play()}else await waitForImage(node,()=>stopped)}
  catch{prepared.delete(index);release(node);report(item,z,item.type==='video'?'No se pudo preparar o reproducir el vídeo':'No se pudo mostrar la imagen');transitioning=false;if(!stopped)setTimeout(()=>show((index+1)%z.items.length),750);return}
  if(stopped)return;const involvesVideo=item.type==='video'||previous?.tagName==='VIDEO',transitionType=item.transition||z.transition,transitionMs=!involvesVideo&&transitionType==='fade'?(item.transition_ms??z.transition_ms??0):0;node.style.transitionDuration=transitionMs+'ms';node.classList.add('active');active=node;currentIndex=index;currentItems[z.key]=item.id;
  if(previous&&previous!==node){if(previous.tagName==='VIDEO')previous.pause();previous.classList.remove('active');const previousIndex=Number(previous.dataset.index);setTimeout(()=>{prepared.delete(previousIndex);release(previous)},transitionMs)}
  if(item.type==='video'){node.loop=z.items.length===1;let stallTimer=null,reported=false;const resumed=()=>{clearTimeout(stallTimer);stallTimer=null;offline.classList.remove('buffering')},buffering=()=>{if(active!==node||stopped)return;offline.classList.add('buffering');if(!stallTimer)stallTimer=setTimeout(()=>{if(!reported){reported=true;report(item,z,'El vídeo se quedó sin búfer durante la reproducción')}},VIDEO_STALL_REPORT_MS)};node.onplaying=resumed;node.oncanplay=resumed;node.onwaiting=buffering;node.onstalled=buffering;node.onerror=()=>{resumed();if(active===node&&!stopped){report(item,z,'Error de decodificación o lectura durante la reproducción');prepared.delete(index);release(node);active=null;transitioning=false;setTimeout(()=>show((index+1)%z.items.length),750)}};if(!node.loop)node.onended=()=>show((index+1)%z.items.length)}else timer=setTimeout(()=>show((index+1)%z.items.length),item.duration_ms||10000);
  transitioning=false;prepareNext();
 };
 show(0);
 return()=>{stopped=true;clearTimeout(timer);prepared.forEach(release);prepared.clear()};
}
async function load(){try{const r=await fetch(configUrl,{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();connected=true;offline.style.display='none';if(!d.schedule_active){fallback(d.fallback_url);return}if(d.config){localStorage.setItem('simpleview-config',JSON.stringify(d.config));render(d.config)}else fallback(d.fallback_url)}catch(e){connected=false;offline.style.display='block';const cached=localStorage.getItem('simpleview-config');if(!config&&cached)render(JSON.parse(cached))}}
async function poll(){if(PREVIEW)return;try{const d=await(await fetch('/api/display/version',{cache:'no-store'})).json();if(d.reload_token!==reloadToken){location.reload();return}if(d.version!==version||!d.schedule_active)await load()}catch(e){connected=false;offline.style.display='block'}}
function report(item,z,message){if(PREVIEW)return;fetch('/api/display/error',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({media_asset_id:item.id,zone_key:z.key,version,message})}).catch(()=>{})}
function heartbeat(){if(PREVIEW)return;fetch('/api/display/heartbeat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({display_key:'main-display',version,width:innerWidth,height:innerHeight,state:connected?'online':'offline',current_items:currentItems})}).catch(()=>{})}
load();setInterval(poll,2500);setInterval(heartbeat,5000);document.addEventListener('contextmenu',e=>e.preventDefault());
</script></body></html>
