<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $preview ? 'Vista previa' : 'Simple View' }}</title>
<style>
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#000;color:#fff;font-family:system-ui,sans-serif;user-select:none}.stage{position:fixed;inset:0;display:grid;background:#000}.stage.preview{position:relative;width:min(100vw,1280px);aspect-ratio:16/9;margin:auto;top:50%;transform:translateY(-50%);box-shadow:0 0 0 1px #444}.zone{position:relative;overflow:hidden;background:#000}.zone .item{position:absolute;inset:0;width:100%;height:100%;opacity:0;transition-property:opacity}.zone .item.active{opacity:1}.zone img,.zone video{width:100%;height:100%;display:block;background:#000}.full{grid-template:1fr/1fr}.columns{grid-template:1fr/1fr 1fr}.rows{grid-template:1fr 1fr/1fr}.grid{grid-template:1fr 1fr/1fr 1fr}.right_sidebar{grid-template:1fr 1fr/7fr 3fr}.right_sidebar .zone:nth-child(3){grid-column:2;grid-row:1/3}.left_sidebar{grid-template:1fr 1fr/3fr 7fr}.left_sidebar .zone:nth-child(3){grid-column:1;grid-row:1/3}.left_sidebar .zone:nth-child(1),.left_sidebar .zone:nth-child(2){grid-column:2}.badge{position:fixed;z-index:10;top:12px;right:12px;background:#111c;padding:6px 10px;border-radius:6px;font-size:13px}.offline{position:fixed;bottom:8px;right:8px;width:8px;height:8px;border-radius:50%;background:#f59e0b;display:none}
</style></head><body><div id="stage" class="stage {{ $preview?'preview':'' }}"></div>@if($preview)<div class="badge">Vista previa</div>@endif<div id="offline" class="offline"></div>
<script>
const PREVIEW=@json($preview), stage=document.querySelector('#stage'), offline=document.querySelector('#offline');let config=null,version=0,runners=[],connected=true,currentItems={};
const qs=new URLSearchParams(location.search), configUrl=PREVIEW?'/api/preview/config?layout='+encodeURIComponent(qs.get('layout')||''):'/api/display/config';
function stop(){runners.forEach(r=>r());runners=[];stage.querySelectorAll('video').forEach(v=>{v.pause();v.removeAttribute('src');v.load()})}
function render(c){stop();config=c;version=c?.version||0;stage.className='stage '+(PREVIEW?'preview ':'')+(c?.template||'full');stage.innerHTML='';if(!c)return;c.zones.forEach(z=>{const el=document.createElement('div');el.className='zone';stage.appendChild(el);runners.push(runZone(el,z))})}
function fallback(url){stop();stage.innerHTML=url?`<img src="${url}" style="width:100%;height:100%;object-fit:contain">`:'';stage.className='stage full'}
function runZone(el,z){let stopped=false,index=0,timer=null,active=null;const next=()=>{if(stopped||!z.items.length)return;const item=z.items[index++%z.items.length],node=document.createElement(item.type==='video'?'video':'img'),previous=active;node.className='item';node.style.transitionDuration=(z.transition==='fade'?z.transition_ms:0)+'ms';node.style.objectFit=item.fit||'cover';if(item.type==='video'){node.muted=true;node.playsInline=true;node.autoplay=true;node.src=item.url;node.onended=next;node.onerror=()=>{report(item,z,'No se pudo reproducir el vídeo');node.remove();next()}}else{node.src=item.url;node.onerror=()=>{report(item,z,'No se pudo mostrar la imagen');node.remove();next()};timer=setTimeout(next,item.duration_ms||10000)}el.appendChild(node);requestAnimationFrame(()=>node.classList.add('active'));if(previous){previous.classList.remove('active');setTimeout(()=>previous.remove(),z.transition_ms||0)}active=node;currentItems[z.key]=item.id};next();return()=>{stopped=true;clearTimeout(timer)}}
async function load(){try{const r=await fetch(configUrl,{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();connected=true;offline.style.display='none';if(!d.schedule_active){fallback(d.fallback_url);return}if(d.config){localStorage.setItem('simpleview-config',JSON.stringify(d.config));render(d.config)}else fallback(d.fallback_url)}catch(e){connected=false;offline.style.display='block';const cached=localStorage.getItem('simpleview-config');if(!config&&cached)render(JSON.parse(cached))}}
async function poll(){if(PREVIEW)return;try{const d=await(await fetch('/api/display/version',{cache:'no-store'})).json();if(d.version!==version||!d.schedule_active)await load()}catch(e){connected=false;offline.style.display='block'}}
function report(item,z,message){if(PREVIEW)return;fetch('/api/display/error',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({media_asset_id:item.id,zone_key:z.key,version,message})}).catch(()=>{})}
function heartbeat(){if(PREVIEW)return;fetch('/api/display/heartbeat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({display_key:'main-display',version,width:innerWidth,height:innerHeight,state:connected?'online':'offline',current_items:currentItems})}).catch(()=>{})}
load();setInterval(poll,2500);setInterval(heartbeat,5000);document.addEventListener('contextmenu',e=>e.preventDefault());
</script></body></html>
