<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Diagnóstico · Simple View</title>
<style>:root{font-family:Inter,system-ui,sans-serif;color:#172033;background:#f5f7fa}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1050px;margin:auto;padding:24px}.top{display:flex;gap:12px;align-items:center}.top h1{flex:1}.btn{border:1px solid #ccd3df;background:#fff;border-radius:8px;padding:10px 14px;text-decoration:none;color:#172033;font-weight:650;cursor:pointer}.primary{background:#4f46e5;color:#fff;border-color:#4f46e5}.card{background:#fff;border:1px solid #dfe3eb;border-radius:12px;padding:18px;margin:16px 0}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.metric{background:#f8fafc;border-radius:8px;padding:12px}.metric b{display:block;font-size:24px}.flash{padding:12px;border-radius:8px;background:#ecfdf3}.flash.error{background:#fef3f2;color:#b42318}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px;border-bottom:1px solid #e4e7ec;vertical-align:top}.badge{display:inline-block;padding:4px 8px;border-radius:99px;background:#ecfdf3;color:#067647;font-weight:700}.badge.warning{background:#fffaeb;color:#b54708}.badge.error{background:#fef3f2;color:#b42318}small{color:#667085}@media(max-width:700px){.summary{grid-template-columns:1fr 1fr}.wrap{padding:12px}.top{flex-wrap:wrap}.top h1{width:100%}}</style></head>
<body><main class="wrap"><div class="top"><a class="btn" href="/admin">← Panel</a><h1>Diagnóstico y reparación</h1><a class="btn" href="{{ route('system-doctor.index') }}">Comprobar de nuevo</a></div>
@if(isset($status))<p class="flash {{ $result['ok']?'':'error' }}">{{ $status }}</p>@endif
<section class="card"><div class="summary"><div class="metric">Comprobaciones<b>{{ $result['summary']['checks'] }}</b></div><div class="metric">Errores<b>{{ $result['summary']['errors'] }}</b></div><div class="metric">Avisos<b>{{ $result['summary']['warnings'] }}</b></div><div class="metric">Reparaciones<b>{{ $result['summary']['repairs'] }}</b></div></div><p><small>Ejecutado: {{ $result['checked_at'] }} · Duración: {{ $result['duration_ms'] }} ms · Modo: {{ $result['mode']==='repair'?'reparación':'solo comprobación' }}</small></p></section>
<section class="card"><table><thead><tr><th>Prueba</th><th>Estado</th><th>Detalle</th></tr></thead><tbody>@foreach($result['checks'] as $check)<tr><td>{{ $check['label'] }}</td><td><span class="badge {{ $check['status'] }}">{{ ['ok'=>'Correcto','warning'=>'Aviso','error'=>'Error'][$check['status']] }}</span></td><td>{{ $check['detail'] }}</td></tr>@endforeach</tbody></table></section>
<section class="card"><h2>Reparación segura</h2><p>Crea directorios ausentes, aplica migraciones pendientes, limpia cachés regenerables y vuelve a medir el almacenamiento. No elimina multimedia, diseños, copias ni trabajos fallidos.</p><form method="post" action="{{ route('system-doctor.repair') }}" onsubmit="return confirm('Se ejecutarán reparaciones seguras y comprobaciones. ¿Continuar?')">@csrf<button class="btn primary">Comprobar y reparar</button></form><p><small>Los fallos de Docker, red, systemd o permisos de root deben repararse por Bash/SSH.</small></p></section>
</main></body></html>
