<?php
namespace Tests\Feature;
use App\Models\BusinessHour; use App\Models\Layout; use App\Models\MediaAsset; use App\Models\Setting; use App\Models\User;
use App\Services\PublicationService; use App\Services\ScheduleService; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Carbon; use Illuminate\Support\Facades\Storage; use Tests\TestCase;
use App\Filament\Widgets\ForceDisplayReload; use Livewire\Livewire;
class SimpleViewFlowTest extends TestCase {
 use RefreshDatabase;
 public function test_administrator_can_open_main_sections():void{if(!extension_loaded('intl'))$this->markTestSkipped('Filament requiere intl.');$u=User::factory()->create(['username'=>'admin']);$this->actingAs($u);foreach(['/admin','/admin/media-assets','/admin/media-assets/create','/admin/layouts','/admin/layouts/create','/admin/business-hours','/admin/business-hours/1/edit','/admin/settings','/admin/settings/1/edit','/admin/backups'] as $url)$this->get($url)->assertSuccessful();}
 public function test_a_draft_can_be_published_as_immutable_snapshot():void{Storage::fake('media');Storage::disk('media')->put('photo.jpg','image');$u=User::factory()->create();$m=MediaAsset::create(['display_name'=>'Foto','original_filename'=>'photo.jpg','storage_path'=>'photo.jpg','mime_type'=>'image/jpeg','media_type'=>'image','extension'=>'jpg','file_size'=>5,'sha256'=>str_repeat('a',64),'width'=>100,'height'=>100,'status'=>'ready']);$l=Layout::create(['name'=>'Principal','template_key'=>'full','state'=>'draft']);$z=$l->zones()->create(['zone_key'=>'zone_1','position'=>1]);$z->items()->create(['media_asset_id'=>$m->id,'sort_order'=>0]);$p=app(PublicationService::class)->publish($l,$u->id);$this->assertSame('published',$p->state);$this->assertSame(1,$p->version);$this->assertSame('full',$p->snapshot_json['template']);$this->getJson('/api/display/version')->assertOk()->assertJsonPath('version',1);}
 public function test_weekly_schedule_and_overrides_are_respected():void{BusinessHour::where('weekday',1)->update(['is_closed'=>false,'first_start'=>'09:00','first_end'=>'18:00']);$service=app(ScheduleService::class);$this->assertTrue($service->isActive(Carbon::parse('2026-07-13 10:00','Europe/Madrid')));$this->assertFalse($service->isActive(Carbon::parse('2026-07-13 20:00','Europe/Madrid')));Setting::where('key','playback_override')->update(['value'=>'force']);$this->assertTrue($service->isActive(Carbon::parse('2026-07-13 20:00','Europe/Madrid')));}
 public function test_display_heartbeat_is_recorded():void{$this->postJson('/api/display/heartbeat',['display_key'=>'main-display','version'=>2,'width'=>1920,'height'=>1080,'state'=>'online'])->assertOk();$this->assertDatabaseHas('display_statuses',['display_key'=>'main-display','loaded_publication_version'=>2]);}
 public function test_administrator_can_force_a_full_player_reload():void{$this->actingAs(User::factory()->create());Livewire::test(ForceDisplayReload::class)->call('forceReload');$token=Setting::valueOf('display_reload_token');$this->assertNotEmpty($token);$this->getJson('/api/display/version')->assertOk()->assertJsonPath('reload_token',$token);$this->get('/display')->assertOk()->assertSee($token,false);}
}
