<?php
namespace App\Http\Controllers;
use App\Models\DisplayStatus; use App\Models\Layout; use App\Models\PlaybackError; use App\Models\MediaAsset; use App\Models\Setting; use App\Services\PublicationService; use App\Services\ScheduleService; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\View\View;
class DisplayController extends Controller {
 public function display():View{return view('player',['preview'=>false,'reloadToken'=>(string)Setting::valueOf('display_reload_token','')]);}
 public function preview():View{return view('player',['preview'=>true,'reloadToken'=>'']);}
 public function version(ScheduleService $schedule):JsonResponse{$layout=Layout::where('state','published')->latest('version')->first();return response()->json(['version'=>$layout?->version??0,'reload_token'=>(string)Setting::valueOf('display_reload_token',''),'schedule_active'=>$schedule->isActive(),'server_time'=>now()->toIso8601String()]);}
 public function config(PublicationService $service,ScheduleService $schedule):JsonResponse{$layout=Layout::where('state','published')->latest('version')->first();$fallback=MediaAsset::find(Setting::valueOf('fallback_media_asset_id'));return response()->json(['schedule_active'=>$schedule->isActive(),'fallback_url'=>$fallback?route('media.stream',$fallback):null,'config'=>$layout?($layout->snapshot_json?:$service->config($layout)):null]);}
 public function previewConfig(Request $request,PublicationService $service):JsonResponse{$layout=Layout::where('state','draft')->findOrFail($request->integer('layout'));return response()->json(['schedule_active'=>true,'config'=>$service->config($layout)]);}
 public function heartbeat(Request $request):JsonResponse{$data=$request->validate(['display_key'=>'required|string|max:100','version'=>'nullable|integer','width'=>'nullable|integer','height'=>'nullable|integer','state'=>'required|string|max:32','current_items'=>'nullable|array']);DisplayStatus::updateOrCreate(['display_key'=>$data['display_key']],['last_seen_at'=>now(),'loaded_publication_version'=>$data['version']??0,'screen_width'=>$data['width']??null,'screen_height'=>$data['height']??null,'state'=>$data['state'],'current_items_json'=>$data['current_items']??[]]);return response()->json(['ok'=>true]);}
 public function error(Request $request):JsonResponse{$data=$request->validate(['media_asset_id'=>'nullable|integer','zone_key'=>'nullable|string','version'=>'nullable|integer','message'=>'required|string|max:2000','context'=>'nullable|array']);PlaybackError::create(['media_asset_id'=>$data['media_asset_id']??null,'zone_key'=>$data['zone_key']??null,'publication_version'=>$data['version']??null,'message'=>$data['message'],'context_json'=>$data['context']??null,'occurred_at'=>now()]);return response()->json(['ok'=>true]);}
}
