<?php
namespace App\Http\Controllers;
use App\Models\Layout; use App\Models\MediaAsset; use App\Services\LayoutDeletionService; use App\Services\MediaDeletionService; use App\Services\StorageCleanupService; use App\Services\StorageMetricsService; use Illuminate\Http\Request;
class StorageController extends Controller {
 public function index(Request $request,StorageMetricsService $metrics){$m=$metrics->current();$filters=$request->validate(['type'=>'nullable|in:image,video','q'=>'nullable|string|max:80','unused'=>'nullable|boolean','sort'=>'nullable|in:size,name,oldest,newest,last_used']);$media=MediaAsset::withCount('playlistItems')->when($filters['type']??null,fn($q,$type)=>$q->where('media_type',$type))->when($filters['q']??null,fn($q,$term)=>$q->where('display_name','like','%'.$term.'%'))->when($filters['unused']??false,fn($q)=>$q->doesntHave('playlistItems'));match($filters['sort']??'size'){ 'name'=>$media->orderBy('display_name'), 'oldest'=>$media->orderBy('created_at'), 'newest'=>$media->latest(), 'last_used'=>$media->orderByDesc('last_used_at'), default=>$media->orderByDesc('file_size')};$largest=(clone $media)->limit(50)->get();$unused=MediaAsset::withCount('playlistItems')->doesntHave('playlistItems')->orderByDesc('file_size')->limit(100)->get();$inactiveLayouts=Layout::withCount('zones')->where('state','<>','published')->latest('updated_at')->limit(50)->get();return view('storage',['metrics'=>$m,'largest'=>$largest,'unused'=>$unused,'inactiveLayouts'=>$inactiveLayouts,'filters'=>$filters]);}
 public function refresh(StorageMetricsService $metrics){$metrics->measure();return back()->with('status','Métricas actualizadas.');}
 public function cleanup(Request $request,StorageCleanupService $cleanup,MediaDeletionService $deletion){$data=$request->validate(['media'=>'required|array','media.*'=>'integer','detach_inactive'=>'sometimes|boolean']);$assets=MediaAsset::whereIn('id',$data['media'])->get();$result=$deletion->bulk($assets,(int)auth()->id(),(bool)($data['detach_inactive']??false));$cleanup->cleanup(['temp'=>true,'orphan_thumbnails'=>true],true);return back()->with('status',$result['deleted'].' contenidos eliminados. '.$result['blocked'].' bloqueados. Espacio liberado: '.number_format($result['bytes']/1048576,1).' MB.');}
 public function deleteLayouts(Request $request,LayoutDeletionService $deletion){$data=$request->validate(['layouts'=>'required|array','layouts.*'=>'integer']);$layouts=Layout::whereIn('id',$data['layouts'])->get();$result=$deletion->bulk($layouts,(int)auth()->id());return back()->with('status',$result['deleted'].' diseños eliminados. '.$result['blocked'].' bloqueados. Los archivos multimedia se conservan.');}
}
