<?php
namespace App\Http\Controllers;
use App\Filament\Resources\LayoutResource; use App\Models\Layout; use App\Models\MediaAsset; use App\Services\MediaDeletionService; use App\Services\MediaIngestionService; use App\Services\PublicationService; use App\Services\UploadCapacityService; use App\Services\WebEmbedService; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Validation\Rule;
class VisualEditorController extends Controller {
 private function enabled():void{abort_unless(config('simpleview.visual_editor_enabled'),404);}
 private function draft(Layout $layout):void{abort_unless($layout->state==='draft',403,'Solo se pueden editar borradores.');}
 public function show(Layout $layout){$this->enabled();$this->draft($layout);return view('visual-editor',['layout'=>$layout,'templates'=>LayoutResource::templates()]);}
 public function state(Layout $layout){$this->draft($layout);return response()->json($this->payload($layout));}
 public function preflight(Request $request,UploadCapacityService $capacity){$data=$request->validate(['sizes'=>'required|array|max:100','sizes.*'=>'integer|min:1']);$result=$capacity->check(array_sum($data['sizes']));return response()->json(['allowed'=>$result['allowed'],'required_bytes'=>$result['required_bytes'],'shortfall_bytes'=>$result['shortfall_bytes'],'message'=>$result['allowed']?'Hay espacio disponible.':'No hay espacio suficiente para completar la subida manteniendo la reserva protegida.'], $result['allowed']?200:422);}
 public function save(Request $request,Layout $layout){$this->draft($layout);$data=$request->validate(['name'=>'required|string|max:255','template_key'=>['required',Rule::in(array_keys(LayoutResource::templates()))],'zones'=>'required|array|min:1|max:4','zones.*.key'=>'required|string|max:32','zones.*.image_fit_default'=>['required',Rule::in(['cover','contain'])],'zones.*.image_duration_default_ms'=>'required|integer|min:250|max:86400000','zones.*.transition_type'=>['required',Rule::in(['cut','fade'])],'zones.*.transition_duration_ms'=>'required|integer|min:0|max:10000','zones.*.items'=>'array','zones.*.items.*.media_asset_id'=>'required|integer|exists:media_assets,id','zones.*.items.*.image_duration_ms'=>'nullable|integer|min:250|max:86400000','zones.*.items.*.image_fit'=>['nullable',Rule::in(['cover','contain'])],'zones.*.items.*.transition_type'=>['nullable',Rule::in(['cut','fade'])],'zones.*.items.*.transition_duration_ms'=>'nullable|integer|min:0|max:10000']);
  if(count($data['zones'])!==LayoutResource::zoneCount($data['template_key']))return response()->json(['message'=>'La cantidad de zonas no corresponde a la plantilla.'],422);
  $webIds=MediaAsset::whereIn('id',collect($data['zones'])->flatMap(fn($z)=>collect($z['items']??[])->pluck('media_asset_id'))->filter()->all())->where('media_type','web_embed')->pluck('id')->all();
  foreach($data['zones'] as $zoneData)if(collect($zoneData['items']??[])->contains(fn($item)=>in_array((int)$item['media_asset_id'],$webIds,true))&&count($zoneData['items']??[])>1)return response()->json(['message'=>'AIMHARDER debe ocupar una zona completa. Vacía la zona o utiliza otra.'],422);
  DB::transaction(function()use($layout,$data){$layout->update(['name'=>$data['name'],'template_key'=>$data['template_key']]);$keep=[];foreach(array_values($data['zones']) as $position=>$zoneData){$zone=$layout->zones()->updateOrCreate(['zone_key'=>$zoneData['key']],['position'=>$position+1,'image_fit_default'=>$zoneData['image_fit_default'],'image_duration_default_ms'=>$zoneData['image_duration_default_ms'],'transition_type'=>$zoneData['transition_type'],'transition_duration_ms'=>$zoneData['transition_duration_ms']]);$keep[]=$zone->id;$zone->items()->delete();foreach(array_values($zoneData['items']??[]) as $order=>$item)$zone->items()->create(['media_asset_id'=>$item['media_asset_id'],'sort_order'=>$order,'image_duration_ms'=>$item['image_duration_ms']??null,'image_fit'=>$item['image_fit']??null,'transition_type'=>$item['transition_type']??null,'transition_duration_ms'=>$item['transition_duration_ms']??null]);}$layout->zones()->whereNotIn('id',$keep)->delete();});
  return response()->json(['saved_at'=>now()->toIso8601String(),'state'=>$this->payload($layout)]);
 }
 public function upload(Request $request,Layout $layout,MediaIngestionService $ingestion){$this->draft($layout);$request->validate(['zone_key'=>'required|string|max:32','files'=>'required|array|max:20','files.*'=>['file','mimetypes:image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime']]);$items=[];foreach($request->file('files') as $file){try{$media=$ingestion->ingest($file);$items[]=$this->mediaPayload($media);}catch(\Throwable $e){$items[]=['name'=>$file->getClientOriginalName(),'error'=>$e->getMessage()];}}return response()->json(['items'=>$items]);}
 public function createWebEmbed(Request $request,Layout $layout,WebEmbedService $web){$this->draft($layout);$data=$request->validate(['name'=>'required|string|max:120','url'=>'required|string|max:2048','refresh_interval_minutes'=>['required','integer',Rule::in([0,5,15,30,60])],'interaction_enabled'=>'sometimes|boolean','scroll_mode'=>['required',Rule::in(['full','auto','hidden'])],'fallback_media_asset_id'=>'nullable|integer|exists:media_assets,id']);$media=$web->create($data);return response()->json(['item'=>$this->mediaPayload($media)]);}
 public function testWebEmbed(Request $request,WebEmbedService $web){$data=$request->validate(['url'=>'required|string|max:2048']);return response()->json($web->connectivity($data['url']));}
 public function previewWebEmbed(Request $request,WebEmbedService $web){$data=$request->validate(['url'=>'required|string|max:2048','name'=>'nullable|string|max:120','interaction'=>'nullable|boolean']);$validated=$web->validateUrl($data['url']);return view('web-embed-preview',['url'=>$validated['url'],'name'=>$data['name']??'WOD del día','interaction'=>(bool)($data['interaction']??false)]);}
 public function mediaUses(Layout $layout,MediaAsset $media,MediaDeletionService $deletion){$this->draft($layout);return response()->json($deletion->classify($media));}
 public function deleteMedia(Request $request,Layout $layout,MediaAsset $media,MediaDeletionService $deletion){$this->draft($layout);$data=$request->validate(['detach_inactive'=>'sometimes|boolean']);$result=$deletion->delete($media,(int)auth()->id(),(bool)($data['detach_inactive']??false));return response()->json($result,$result['deleted']?200:422);}
 public function publish(Layout $layout,PublicationService $publication){$this->draft($layout);try{$published=$publication->publish($layout,(int)auth()->id());return response()->json(['message'=>'Pantalla publicada. El reproductor se actualizará en un máximo de tres segundos.','version'=>$published->version]);}catch(\Illuminate\Validation\ValidationException $e){return response()->json(['message'=>collect($e->errors())->flatten()->first()],422);}catch(\Throwable){return response()->json(['message'=>'No se pudo publicar. Revisa el almacenamiento y el contenido de todas las zonas.'],500);}}
 private function payload(Layout $layout):array{$layout->load('zones.items.media.fallbackMedia');return['layout'=>['id'=>$layout->id,'name'=>$layout->name,'template_key'=>$layout->template_key,'state'=>$layout->state,'zones'=>$layout->zones->map(fn($z)=>['key'=>$z->zone_key,'image_fit_default'=>$z->image_fit_default,'image_duration_default_ms'=>$z->image_duration_default_ms,'transition_type'=>$z->transition_type,'transition_duration_ms'=>$z->transition_duration_ms,'items'=>$z->items->map(fn($i)=>array_merge($this->mediaPayload($i->media),['media_asset_id'=>$i->media_asset_id,'image_duration_ms'=>$i->image_duration_ms,'image_fit'=>$i->image_fit,'transition_type'=>$i->transition_type,'transition_duration_ms'=>$i->transition_duration_ms]))->values()])->values()],'media'=>MediaAsset::where('status','ready')->latest()->limit(500)->get()->map(fn($m)=>$this->mediaPayload($m)),'fallback_images'=>MediaAsset::where('media_type','image')->where('status','ready')->orderBy('display_name')->get(['id','display_name'])->map(fn($m)=>['id'=>$m->id,'name'=>$m->display_name])];}
 private function mediaPayload(MediaAsset $m):array{if($m->media_type==='web_embed'){$host=parse_url((string)$m->embed_url,PHP_URL_HOST);return['id'=>$m->id,'media_asset_id'=>$m->id,'name'=>$m->display_name,'type'=>'web_embed','provider'=>$m->provider,'url'=>$m->embed_url,'domain'=>$host,'size'=>0,'thumbnail'=>null,'options'=>$m->embed_options_json?:[],'fallback_media_asset_id'=>$m->fallback_media_asset_id,'validation_status'=>$m->validation_status?:'pending','needs_internet'=>true];}return['id'=>$m->id,'media_asset_id'=>$m->id,'name'=>$m->display_name,'type'=>$m->media_type,'mime'=>$m->mime_type,'size'=>$m->file_size,'width'=>$m->width,'height'=>$m->height,'duration_ms'=>$m->duration_ms,'thumbnail'=>route('media.thumbnail',$m),'needs_internet'=>false];}
}
